export default [
  'Entry SD upgrade...',
  'dloading module MDSASA.....',
  'dloading module CRC.....',
  'mdrsg_verify success',
  '',
  'md5 verify success',
  'dloading module CRC.....',
  'warn version string-G700-100 V100R0014CHN00B105_Debug',
  '',
  '',
  'dloading module VERL_ISF.....',
  'Main Version from Property is G700-100 V100R0014CHN00B105_Debug',
  'Main version check: thie market is name, go to continue..',
  'current version in VERL_ISF. allto to update.',
  'dloading module MBR.....success',
  'dloading module LER1....success',
  'dloading module LER2.....success',
  'dloading module UBOOT.....success',
  'dloading module RECOVERY.....success',
  'dloading module SECRD.....success',
  'dloading module LOGO.....success',
  'dloading module SYSTEM.....',
  'waiting.....',
  'waiting.....',
  'waiting.....',
  'waiting.....',
  'waiting.....',
  'waiting.....',
  'waiting.....',
  'waiting.....',
  'waiting.....',
  'waiting.....',
  'waiting.....',
  'waiting.....',
  'waiting.....',
  'dloading module BLUETOOTH.....success',
  'dloading module WIFI.....success',
  'dloading module CPUSYSTEM.....success',
  'dloading module BLUETOOTH.....success',
  'system loading completed',
  'ready to restart.....',
  'ready to restart.....'
]